name: build-fe

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push fe image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/fe:develop
          build-args: |
            API_URL=http://be:8000
            NEXT_PUBLIC_CLOUDFRONT_URL=https://cdn.need4deed.org/images
            NEXT_PUBLIC_CLOUDFRONT_DATA_URL=https://cdn.need4deed.org/data
            GIT_COMMIT_SHA=${{ github.sha }}
